spring:
  application:
    name: currency-conversion-factor  datasource:    url: jdbc:h2:mem:currency
    username: sa
    password: password
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      refresh:
        enable: false
server:  port: 8080